name: Change Clayoquot
favicon: null
layout_spectrum: 0.3337706574238837
typography_spectrum: 0.8057627244852483
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4163c4'
    - '#c4a9d2'
    - '#bbd2fb'
    - '#887fb6'
    - '#10112a'
  brandStrength: 0.8655678764916956
  lightness: 0.17489326419308782
  saturation: 0.3422260908409953
  rhythmicContrast: 0.3490258555393666
purpose: []
